version: '3'

services:
  backend:
      build: ./api
      image: app-backend
      container_name: app-backend
      command: bash -c "python manage.py makemigrations && python manage.py migrate  && python manage.py runserver 8000"
      ports:
        - 8000:8000
  frontend:
      build: ./frontend
      image: app-frontend
      container_name: app-frontend
      ports:
        - 3000:80
      