version: '3'

services:

  backend-hng:
      build: ./api
      image: app-backend-hng
      container_name: app-backend-hng
      command: bash -c "python manage.py makemigrations && python manage.py migrate  && python manage.py runserver 0.0.0.0:8000"
      ports:
        - 8000:8000

  frontend-hng:
      build: ./frontend
      image: app-frontend-hng
      container_name: app-frontend-hng
      ports:
        - 3000:80

      